1. Rondo Form is a type of musical structure, in which there is a recurring
theme/refrain, notated as A. Here are the rules for valid rondo forms:
- Rondo forms always start and end with an A section.
- In between the A sections, there should be contrasting sections notated as
B, then C, then D, etc... No letter should be skipped.
- There shouldn't be any repeats in the sequence (such as ABBACCA).
Create a function which validates whether a given string is a valid Rondo
Form.
Examples
valid_rondo("ABACADAEAFAGAHAIAJA") ➞ True
valid_rondo("ABA") ➞ True
valid_rondo("ABBACCA") ➞ False
valid_rondo("ACAC") ➞ False
valid_rondo("A") ➞ False


In [20]:
def valid_rondo (string): 
    if not string.endswith ("A") and string.startswith ("A"): 
        return False
    elif len (string) == 1 : 
        return False 
    for i in range (len (string)-1) : 
            if string [i] == string [i + 1]: 
                return False
    for i in range (0 , len (string),  2): 
        if string [ i ] != "A": 
            return False
    for i in range (1 , len (string)-2,  2): 
        if ord (string [ i ]) != ord (string [ i + 2 ]) -1 : 
            return False
    else : 
        return True

print (valid_rondo("ABACADAEAFAGAHAIAJA") )
print (valid_rondo("ABA") )
print (valid_rondo("ABBACCA") )
print (valid_rondo("ACAC") )
print (valid_rondo("A") )


True
True
False
False
False


In [ ]:
2. Create a function that returns the whole of the first sentence which
contains a specific word. Include the full stop at the end of the sentence.
Examples
txt = "I have a cat. I have a mat. Things are going swell."
sentence_searcher(txt, "have") ➞ "I have a cat."
sentence_searcher(txt, "MAT") ➞ "I have a mat."
sentence_searcher(txt, "things") ➞ "Things are going swell."
sentence_searcher(txt, "flat") ➞ "


In [99]:
def sentence_searcher (sentence, key): 
    import re
    pattern = f"[a-zA-Z ]*{key.lower()}[a-zA-Z ]*(?=[.])"
    a = re.findall (pattern, sentence)
    if a == []: 
        print ("")
    else : 
        print (a [0] )

txt = "I have a cat. I have a mat. things are going swell."
sentence_searcher(txt, "have")
sentence_searcher(txt, "MAT") 
sentence_searcher(txt, "things") 
sentence_searcher(txt, "flat") 


I have a cat
 I have a mat
 things are going swell



In [ ]:
3. Given a number, find the "round "of each digit of the number. An integer is
called "round" if all its digits except the leftmost (most significant) are equal to
zero.
- Round numbers: 4000, 1, 9, 800, 90
- Not round numbers: 110, 707, 222, 1001

Create a function that takes a number and returns the "round" of each digit
(except if the digit is zero) as a string. Check out the following examples for
more clarification.
Examples
sum_round(101) ➞ "1 100"
sum_round(1234) ➞ "4 30 200 1000"
sum_round(54210) ➞ "10 200 4000 50000"


In [112]:
def sum_round (num): 
    str_num = str (num)
    lst = []
    i = len(str_num)
    b = 1 
    while i > 0: 
        a = int(str_num [i-1]) * b 
        b = b * 10 
        i = i - 1
        lst.append (a)
    for i in lst: 
        if i > 0 : 
            print (i, end = " ")
    print ("\n")



sum_round(101) 
sum_round(1234) 
sum_round(54210) 

1 100 

4 30 200 1000 

10 200 4000 50000 



In [ ]:
4. Your task, is to create N x N multiplication table, of size n provided in
parameter.
For example, when n is 5, the multiplication table is:
- 1, 2, 3, 4, 5
- 2, 4, 6, 8, 10
- 3, 6, 9, 12, 15
- 4, 8, 12, 16, 20
- 5, 10, 15, 20, 25
This example will result in:
[[1, 2, 3, 4, 5], [2, 4, 6, 8, 10], [3, 6, 9, 12, 15], [4, 8, 12, 16, 20], [5, 10, 15, 20,
25]]
Examples
multiplication_table(1) ➞ [[1]]
multiplication_table(3) ➞ [[1, 2, 3], [2, 4, 6], [3, 6, 9]]


In [157]:
def multiplication_table (num): 
    import numpy as np
    a = np.arange (1, num+1)
    print (a * a[ : , None])
 

multiplication_table(1)
multiplication_table(3) 

[[1 2 3]
 [2 4 6]
 [3 6 9]]


In [ ]:
5. Create a function that returns True if two lines rhyme and False otherwise.
For the purposes of this exercise, two lines rhyme if the last word from each
sentence contains the same vowels.
Examples
does_rhyme("Sam I am!", "Green eggs and ham.") ➞ True
does_rhyme("Sam I am!", "Green eggs and HAM.") ➞ True
# Capitalization and punctuation should not matter.

does_rhyme("You are off to the races", "a splendid day.") ➞ False
does_rhyme("and frequently do?", "you gotta move.") ➞ False

In [161]:
def does_rhyme (str1, str2): 
    lst1 = str1.split(" ")
    lst2 = str2.split(" ")
    lst_word1 = lst1 [-1].lower ()
    lst_word2 = lst2 [-1].lower ()
    vowel = ["a","e","i","o","u"]
    vowel1 = []
    vowel2 = []
    for i in lst_word1 : 
        if i in vowel : 
            vowel1.append (i)
    for i in lst_word2 : 
        if i in vowel : 
            vowel2.append (i)
    if vowel1 == vowel2 : 
        print (True)
    else : 
        print (False)

does_rhyme("Sam I am!", "Green eggs and ham.") 
does_rhyme("Sam I am!", "Green eggs and HAM.")
does_rhyme("You are off to the races", "a splendid day.") 
does_rhyme("and frequently do?", "you gotta move.") 


True
True
False
False
