In [ ]:
1. Create a class Sudoku that takes a string as an argument. 
The string will contain the numbers of a regular 9x9 sudoku board left to right and top to bottom, 
with zeros filling up the empty cells.

Attributes

An instance of the class Sudoku will have one attribute:

   - board: a list representing the board, with sublits for each row, with the numbers as integers. 
        Empty cell represented with 0.

Methods

An instance of the class Sudoku wil have three methods:

   - get_row(n): will return the row in position n.
   - get_col(n): will return the column in position n.
   - get_sqr([n, m]): will return the square in position n if only one argument is given, and the square 
            to which the cell in position (n, m) belongs to if two arguments are given.

Example

game = Sudoku("417950030000000700060007000050009106800600000000003400900005000000430000200701580")


game.board ➞ [
  [4, 1, 7, 9, 5, 0, 0, 3, 0],
  [0, 0, 0, 0, 0, 0, 7, 0, 0],
  [0, 6, 0, 0, 0, 7, 0, 0, 0],
  [0, 5, 0, 0, 0, 9, 1, 0, 6],
  [8, 0, 0, 6, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 3, 4, 0, 0],
  [9, 0, 0, 0, 0, 5, 0, 0, 0],
  [0, 0, 0, 4, 3, 0, 0, 0, 0],
  [2, 0, 0, 7, 0, 1, 5, 8, 0]
]

game.get_row(0) ➞ [4, 1, 7, 9, 5, 0, 0, 3, 0]
game.get_col(8) ➞ [0, 0, 0, 6, 0, 0, 0, 0, 0]
game.get_sqr(1) ➞ [9, 5, 0, 0, 0, 0, 0, 0, 7]
game.get_sqr(1, 8) ➞ [0, 3, 0, 7, 0, 0, 0, 0, 0]
game.get_sqr(8, 3) ➞ [0, 0, 5, 4, 3, 0, 7, 0, 1]


In [35]:
class Sudoku: 
    def __init__ (self, string): 
        import numpy as np
        self.string = string 
        self.board = np.matrix ([[int(string [i]) for i in range (j, j+9) ]  for j in range (0, len (string), 9)])
    
    def get_row (self, n): 
        print (self.board [n]) 
        
    def get_col (self, n): 
        print ([i[0, n] for i in  self.board])

    def get_sqr (self, *args): 
        if len (args) == 1: 
            if args [0] == 0 : 
                print (self.board[0:3, 0:3])
            if args [0] == 1 : 
                print (self.board[0:3, 3:6])
            if args [0] == 2 : 
                print (self.board[0:3, 6:9])
            if args [0] == 3 : 
                print (self.board[3:6, 0:3])
            if args [0] == 4 : 
                print (self.board[3:6, 3:6])
            if args [0] == 5 : 
                print (self.board[3:6, 6:9])
            if args [0] == 6 : 
                print (self.board[6:9, 0:3])
            if args [0] == 7 : 
                print (self.board[6:9, 3:6])
            if args [0] == 8 : 
                print (self.board[6:9, 6:9])
        if len (args) == 2: 
    
            if (args [0] in [0,1,2]) & (args [1] in [0,1,2]): 
                print (self.board[0:3, 0:3])
            if (args [0] in [0,1,2]) & (args [1] in [3,4,5]): 
                print (self.board[0:3, 3:6])
            if (args [0] in [0,1,2]) & (args [1] in [6,7,8]): 
                print (self.board[0:3, 6:9])
        
            if (args [0] in [3,4,5]) & (args [1] in [0,1,2]): 
                print (self.board[3:6, 0:3])
            if (args [0] in [3,4,5]) & (args [1] in [3,4,5]): 
                print (self.board[3:6, 3:6])
            if (args [0] in [3,4,5]) & (args [1] in [6,7,8]): 
                print (self.board[3:6, 6:9])
        
            if (args [0] in [6,7,8]) & (args [1] in [0,1,2]): 
                print (self.board[6:9, 0:3])
            if (args [0] in [6,7,8]) & (args [1] in [3,4,5]): 
                print (self.board[6:9, 3:6])
            if (args [0] in [6,7,8]) & (args [1] in [6,7,8]): 
                print (self.board[6:9, 6:9])
      
game = Sudoku("417950030000000700060007000050009106800600000000003400900005000000430000200701580")
print (game.board)

game.get_row(0) 
game.get_col(8) 
game.get_sqr(0) 
game.get_sqr(1, 8)
game.get_sqr(8, 3)


[[4 1 7 9 5 0 0 3 0]
 [0 0 0 0 0 0 7 0 0]
 [0 6 0 0 0 7 0 0 0]
 [0 5 0 0 0 9 1 0 6]
 [8 0 0 6 0 0 0 0 0]
 [0 0 0 0 0 3 4 0 0]
 [9 0 0 0 0 5 0 0 0]
 [0 0 0 4 3 0 0 0 0]
 [2 0 0 7 0 1 5 8 0]]
[[4 1 7 9 5 0 0 3 0]]
[0, 0, 0, 6, 0, 0, 0, 0, 0]
[[4 1 7]
 [0 0 0]
 [0 6 0]]
[[0 3 0]
 [7 0 0]
 [0 0 0]]
[[0 0 5]
 [4 3 0]
 [7 0 1]]


In [80]:
2. The function input is two non-empty linked lists representing two non-negative integers. 
The digits are stored in reverse order, and each of their nodes contains a single digit. 
Add the two numbers and return the sum as a linked list, in which the digits are also stored in reversed order. 
The class ListNode, building block of the linked list, is defined in the Tests tab.

Class definition

class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next

Examples

lt1 = ListNode(2)
lt1.add_data([4, 3])
lt2 = ListNode(5)
lt2.add_data([6, 4])
# print(lt1.get_data())    # [2, 4, 3]
# print(lt2.get_data())    # [5, 6, 4]
# print(342 + 465)         # 807
add_two_numbers(lt1, lt2).get_data() ➞ [7, 0, 8]

lt1 = ListNode(0)
lt2 = ListNode(0)
# print(lt1.get_data())    # [0]
# print(lt2.get_data())    # [0]
# print(0 + 0)             # 0
add_two_numbers(lt1, lt2).get_data() ➞ [0]

lt1 = ListNode(9)
lt1.add_data([9,9,9,9,9,9])
lt2 = ListNode(9)
lt2.add_data([9,9,9])
# print(lt1.get_data())    # [9, 9, 9, 9, 9, 9, 9]
# print(lt2.get_data())    # [9, 9, 9, 9]
# print(9999999 + 9999)    # 10009998
add_two_numbers(lt1, lt2).get_data() ➞ [8, 9, 9, 9, 0, 0, 0, 1]


SyntaxError: invalid syntax (Temp/ipykernel_13316/1655746662.py, line 1)

In [88]:
class ListNode:
    def __init__(self, val=0, next=None):
        self.val = val
        self.next = next
        self.a = [self.val]
        
    def add_data (self, list): 
        for i in list: 
            self.a.append (i)
            
    def get_data (self): 
        return (self.a)

def add_two_numbers(obj1, obj2): 
    a1 = obj1.get_data ()[::-1]
    str1 = ""
    for i in a1 : 
        str1 += str (i)

    a2 = obj2.get_data ()[::-1]
    str2 = ""
    for i in a2 : 
        str2 += str (i)

    sum = int (str1) + int (str2)
    sum_rev = str (sum)[::-1]
    new_obj = ListNode (int (sum_rev))
    new_obj.a = [int (i) for i in str (new_obj.a [0])]
    return new_obj

lt1 = ListNode(2)
lt1.add_data([4, 3])
lt2 = ListNode(5)
lt2.add_data([6, 4])
print(lt1.get_data())    # [2, 4, 3]
print(lt2.get_data())   # [5, 6, 4]
print(add_two_numbers(lt1, lt2).get_data ())
print ("\n")

lt1 = ListNode(0)
lt2 = ListNode(0)
print(lt1.get_data())   
print(lt2.get_data()) 
print(add_two_numbers(lt1, lt2).get_data ())
print ("\n")

lt1 = ListNode(9)
lt1.add_data([9,9,9,9,9,9])
lt2 = ListNode(9)
lt2.add_data([9,9,9])
print(lt1.get_data())  
print(lt2.get_data()) 
print(add_two_numbers(lt1, lt2).get_data ()) 

        


[2, 4, 3]
[5, 6, 4]
[7, 0, 8]


[0]
[0]
[0]


[9, 9, 9, 9, 9, 9, 9]
[9, 9, 9, 9]
[8, 9, 9, 9, 0, 0, 0, 1]


In [ ]:

3. Write a class called CoffeeShop, which has three instance variables:

   1. name : a string (basically, of the shop)
   2. menu : a list of items (of dict type), with each item containing the item (name of the item), 
      type (whether a food or a drink) and price.
   3. orders : an empty list

and seven methods:

  1. add_order: adds the name of the item to the end of the orders list if it exists on the menu, otherwise, 
      return "This item is currently unavailable!"
  2. fulfill_order: if the orders list is not empty, return "The {item} is ready!". If the orders list is empty, 
      return "All orders have been fulfilled!"
  3. list_orders: returns the item names of the orders taken, otherwise, an empty list.
  4. due_amount: returns the total amount due for the orders taken.
  5. cheapest_item: returns the name of the cheapest item on the menu.
  6. drinks_only: returns only the item names of type drink from the menu.
  7. food_only: returns only the item names of type food from the menu.

IMPORTANT: Orders are fulfilled in a FIFO (first-in, first-out) order.

Examples

tcs.add_order("hot cocoa") ➞ "This item is currently unavailable!"
# Tesha's coffee shop does not sell hot cocoa
tcs.add_order("iced tea") ➞ "This item is currently unavailable!"
# specifying the variant of "iced tea" will help the process

tcs.add_order("cinnamon roll") ➞  "Order added!"
tcs.add_order("iced coffee") ➞ "Order added!"
tcs.list_orders ➞ ["cinnamon roll", "iced coffee"]
# all items of the current order

tcs.due_amount() ➞ 2.17

tcs.fulfill_order() ➞ "The cinnamon roll is ready!"
tcs.fulfill_order() ➞ "The iced coffee is ready!"
tcs.fulfill_order() ➞ "All orders have been fulfilled!"
# all orders have been presumably served

tcs.list_orders() ➞ []
# an empty list is returned if all orders have been exhausted

tcs.due_amount() ➞ 0.0
# no new orders taken, expect a zero payable

tcs.cheapest_item() ➞ "lemonade"
tcs.drinks_only() ➞ ["orange juice", "lemonade", "cranberry juice", "pineapple juice", "lemon iced tea", 
  "vanilla chai latte", "hot chocolate", "iced coffee"]
tcs.food_only() ➞ ["tuna sandwich", "ham and cheese sandwich", "bacon and egg", "steak", "hamburger", "cinnamon roll"]


In [142]:
class CoffeeShop : 
        def __init__ (self, name, menu, orders ): 
                self.name = name 
                self.menu = menu 
                self.orders = orders 

        def list_of_item (self): 
                list = []
                for i in self.menu:
                        for j in  i.keys(): 
                                list.append (j)
                return list

        def add_order (self, item):
                if item in self.list_of_item (): 
                        self.orders.append (item)
                        print ("Order added!")
                else : 
                      print ("This item is currently unavailable!")  

        def list_orders (self): 
                print (self.orders)


        def fulfill_order (self): 
                
                if self.orders == []: 
                        print ( "All orders have been fulfilled!")
                else : 
                        print (f"The {self.orders[0]} is ready!")
                        self.orders.remove (self.orders [0])

        def due_amount (self): 
                sum = 0
                for i in self.orders : 
                        for j in menu : 
                                for m in j.keys(): 
                                        if m == i : 
                                                for n in j.values (): 
                                                        sum += n [1]
                print (sum)

        def cheapest_item(self) :
                price = [] 
                for i in self.menu: 
                        for j in i.values (): 
                                price.append (j[1])
                for i in self.menu: 
                        for j in i.values ():
                                if j[1] == min (price): 
                                        for m in i.keys (): 
                                                print (m)

        def drinks_only(self):
                drink = []
                for i in self.menu: 
                        for j in i.values ():
                                if j[0] == "drink":
                                        for m in i.keys (): 
                                                drink.append (m)
                print (drink) 


        def food_only(self): 
                food = []
                for i in self.menu: 
                        for j in i.values ():
                                if j[0] == "food":
                                        for m in i.keys (): 
                                                food.append (m)
                print (food)  


          
menu = [ {'orange juice': ['drink', 15]}, {'lemonade': ['drink', 10]}, {'cranberry juice': ['drink', 25]}, 
        {'pineapple juice': ['drink', 30]}, {'lemon iced tea': ['drink', 35]}, {'vanilla chai latte': ['drink', 40]}, 
        {'hot chocolate': ['drink', 45]}, {'iced coffee': ['drink', 50]}, {'tuna sandwich': ['food', 55]}, 
        {'ham and cheese sandwich': ['food', 60]}, {'bacon and egg': ['food', 65]}, {'steak': ['food', 70]}, 
        {'hamburger': ['food', 75]}, {'cinnamon roll': ['food', 80]}]
 
tcs = CoffeeShop ("The Coffee Shop", menu, [])
tcs.add_order("hot cocoa")
tcs.add_order("iced tea") 
tcs.add_order("cinnamon roll") 
tcs.add_order("iced coffee")
tcs.list_orders ()
tcs.due_amount()
tcs.fulfill_order() 
tcs.fulfill_order() 
tcs.fulfill_order()
tcs.due_amount()  
tcs.list_orders()
tcs.cheapest_item()
tcs.drinks_only() 
tcs.food_only() 


This item is currently unavailable!
This item is currently unavailable!
Order added!
Order added!
['cinnamon roll', 'iced coffee']
130
The cinnamon roll is ready!
The iced coffee is ready!
All orders have been fulfilled!
0
[]
lemonade
['orange juice', 'lemonade', 'cranberry juice', 'pineapple juice', 'lemon iced tea', 'vanilla chai latte', 'hot chocolate', 'iced coffee']
['tuna sandwich', 'ham and cheese sandwich', 'bacon and egg', 'steak', 'hamburger', 'cinnamon roll']


In [ ]:

4. In this challenge, write a funcion loneliest_number to find the last Lonely number inside a sequence. 
A number is Lonely if the distance from its closest Prime sets a new record of the sequence.

Sequence = from 0 to 3

# Any number lower than 3 doesn't have a Prime preceeding it...
# ...so that you'll consider only its next closest Prime.

0 has distance 2 from its closest Prime (2)
# It's a new record! 0 It's the first lonely number of the sequence
1 has distance 1 from its closest Prime (2)
2 has distance 1 from 3
3 has distance 1 from 2

# The sequence 0 to 3  has only one Lonely number: 0

Sequence = Numbers from 5 to 10

5 has distance 2 from its closest Prime (3 or 7)
# It's a new record! 5 It's the first lonely number of the sequence
6 has distance 1 from 5 or 7
7 has distance 2 from 5
8 has distance 1 from 7
9 has distance 2 from 7 or 11
10 has distance 1 from 11

# The sequence 5 to 10  has only one Lonely number: 5

Sequence = Numbers from 19 to 24

19 has distance 2 from its closest Prime (17)
# It's a new record! 19 It's the first lonely number of the sequence
20 has distance 1 from 19
21 has distance 2 from 5
22 has distance 1 from 23
23 has distance 4 from 17 or 29
# It's a new record! 23 is the second lonely number of the sequence
24 has distance 1 from 23

# The sequence 19 to 24  has two Lonely numbers: 19 and 23

The function loneliest_number must accept two integers lo and hi being the inclusive bounds of the sequence to analyze, and 
returns a dictionay (dict) object with the following keys and values:

   - number: is the last Lonely number found in the given sequence;
   - distance: is the distance of the number from its closest Prime;
   - closest: is the Prime closest to number (if two Primes are equally distant from number, return the higher Prime).

Examples

loneliest_number(0, 22) ➞ {
  number: 0, distance: 2, closest: 2
}

loneliest_number(8, 123) ➞ {
  number: 53, distance: 6, closest: 59
}

loneliest_number(938, 1190) ➞ {
  number: 1140, distance: 11, closest: 1151
}

loneliest_number(120, 1190) ➞ {
  number: 211, distance: 12, closest: 223
}


In [24]:
def loneliest_number (lo, hi): 
    def isPrime (num): 
        if num == 0 : 
            return False 
        if num == 1 : 
            return False 
        if num > 1: 
            for i in range (2, num): 
                if num % i == 0 : 
                    return False 
            return True

    def closest_prime (num):
        a = 1
        while isPrime (num - a) == False : 
            a += 1
        cp_lower =  (num - a)
        # print (cp_lower)

        b = 1
        while isPrime (num + b) == False : 
            b += 1
        cp_higher =  (num + b)
        # print (cp_higher)

        if (num == 0) or (num == 1) or (num == 2): 
            return cp_higher
        else : 
            if num - cp_lower < cp_higher - num : 
                return cp_lower
            else : 
                return cp_higher

    difference  = 0
    lonely_numbers = []
    for i in range (lo, hi+1): 
        # print (closest_prime (i))
        if abs (i - closest_prime (i)) > difference : 
            lonely_numbers.append (i)
            difference = abs (i - closest_prime (i))
    # print (lonely_numbers)
    print ({
    'number': lonely_numbers [-1], 'distance': difference, 'closest': closest_prime (lonely_numbers [-1])
    })

loneliest_number(0, 22) 
loneliest_number(8, 123)
loneliest_number(938, 1190)
loneliest_number(120, 1190) 


    

{'number': 0, 'distance': 2, 'closest': 2}
{'number': 120, 'distance': 7, 'closest': 127}
{'number': 1140, 'distance': 11, 'closest': 1151}
{'number': 211, 'distance': 12, 'closest': 223}
