In [ ]:
1. Create a function that transposes a 2D matrix.

Examples

transpose_matrix([
  [1, 1, 1],
  [2, 2, 2],
  [3, 3, 3]
]) ➞ [
  [1, 2, 3],
  [1, 2, 3],
  [1, 2, 3]
]

transpose_matrix([
  [5, 5],
  [6, 7],
  [9, 1]
]) ➞ [
  [5, 6, 9],
  [5, 7, 1]
]


In [2]:
def transpose_matrix (mat): 
  import numpy as np
  a = np.matrix (mat)
  print (a.T)



transpose_matrix([
  [1, 1, 1],
  [2, 2, 2],
  [3, 3, 3]
])

transpose_matrix([
  [5, 5],
  [6, 7],
  [9, 1]
]) 

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[5 6 9]
 [5 7 1]]


In [3]:
2. Create a function that determines whether a string is a valid hex code.

A hex code must begin with a pound key # and is exactly 6 characters in length. 
Each character must be a digit from 0-9 or an alphabetic character from A-F. 
All alphabetic characters may be uppercase or lowercase.

Examples

is_valid_hex_code("#CD5C5C") ➞ True

is_valid_hex_code("#EAECEE") ➞ True

is_valid_hex_code("#eaecee") ➞ True

is_valid_hex_code("#CD5C58C") ➞ False
# Length exceeds 6

is_valid_hex_code("#CD5C5Z") ➞ False
# Not all alphabetic characters in A-F

is_valid_hex_code("#CD5C&C") ➞ False
# Contains unacceptable character

is_valid_hex_code("CD5C5C") ➞ False
# Missing #

SyntaxError: invalid syntax (Temp/ipykernel_1808/1372483904.py, line 1)

In [17]:
def is_valid_hex_code (str): 
    def is_valid (string): 
        list = "ABCDEFabcdef0123456789"
        for i in string [1:] : 
            if all (map(lambda x : x in list, string [1:])) : 
                return True 
            else : 
                return False
            
    if str [0] != "#": 
        return False
    elif len (str) != 7: 
        return False
    elif is_valid (str): 
        return True 
    else : 
        return False

print (is_valid_hex_code("#CD5C5C") )
print (is_valid_hex_code("#EAECEE") )
print (is_valid_hex_code("#eaecee") )
print (is_valid_hex_code("#CD5C58C") )
print (is_valid_hex_code("#CD5C5Z") )
print (is_valid_hex_code("#CD5C&C") )
print (is_valid_hex_code("CD5C5C") )

True
True
True
False
False
False
False


In [ ]:
3. Given a list of math equations (given as strings), 
return the percentage of correct answers as a string. Round to the nearest whole number.

Examples

mark_maths(["2+2=4", "3+2=5", "10-3=3", "5+5=10"]) ➞ "75%"

mark_maths(["1-2=-2"]), "0%"

mark_maths(["2+3=5", "4+4=9", "3-1=2"]) ➞ "67%"

In [57]:
def mark_maths (lst): 
    import re
    import math
    list = []
    for i in lst : 
        a = re.split ("\=", i)
        # print (a)
        b = re.split ("\+|\-", a [0])
        # print (b)
        if  "+" in a [0]: 
            c = int(b [0]) + int(b [1] ) == int (a [1])
        elif "-" in a [0]: 
            c = int(b [0]) - int(b [1] ) == int (a [1])
        # print (c)
        list.append (c)
    # print (list)
    print (str((round (list.count (True)/len (list)*100)) )+ "%")
    

mark_maths(["2+2=4", "3+2=5", "10-3=3", "5+5=10"]) 
mark_maths(["1-2=-2"])
mark_maths(["2+3=5", "4+4=9", "3-1=2"]) 

75%
0%
67%


In [ ]:
4. There are two players, Alice and Bob, each with a 3-by-3 grid. A referee tells Alice to fill out 
one particular row in the grid (say the second row) by putting either a 1 or a 0 in each box, 
such that the sum of the numbers in that row is odd. The referee tells Bob to fill out one column 
in the grid (say the first column) by putting either a 1 or a 0 in each box, such that the sum of the 
numbers in that column is even.

Alice and Bob win the game if Alice’s numbers give an odd sum, Bob’s give an even sum, and 
(most important) they’ve each written down the same number in the one square where their row 
and column intersect.

Examples

magic_square_game([2, "100"], [1, "101"]) ➞ False

magic_square_game([2, "001"], [1, "101"]) ➞ True

magic_square_game([3, "111"], [2, "011"]) ➞ True

magic_square_game([1, "010"], [3, "101"]) ➞ False

# Two lists, Alice [row, "her choice"], Bob [column, "his choice"]


In [60]:
def magic_square_game (list1, list2): 
    sum = 0 
    for i in list1 [1]: 
        sum += int (i)
    if sum %2 != 1 : 
        return False
    elif list1 [1] [list2 [0]-1] != list2 [1] [list1 [0]-1] : 
        return False 
    else : 
        return True 

print (magic_square_game([2, "100"], [1, "101"]))
print (magic_square_game([2, "001"], [1, "101"]))
print (magic_square_game([3, "111"], [2, "011"]))
print (magic_square_game([1, "010"], [3, "101"]))

False
True
True
False


In [ ]:

5. From point A, an object is moving towards point B at constant velocity va (in km/hr). From point B,
 another object is moving towards point A at constant velocity vb (in km/hr). 
 Knowing this and the distance between point A and B (in km), 
 write a function that returns how much time passes until both objects meet.

Format the output like this:

"2h 23min 34s"

Examples

lets_meet(100, 10, 30) ➞ "2h 30min 0s"

lets_meet(280, 70, 80) ➞ "1h 52min 0s"

lets_meet(90, 75, 65) ➞ "0h 38min 34s"


In [73]:
def lets_meet (dist, va, vb): 
    import datetime, time
    sec = dist / (va + vb)*3600
    times = time.gmtime( sec)
    a = time.strftime ("%Hh %Mmin %Ss", times)
    print (a)

lets_meet(100, 10, 30)
lets_meet(280, 70, 80)
lets_meet(90, 75, 65)

02h 30min 00s
01h 52min 00s
00h 38min 34s
