1. Write a Python Program to find sum of array?

In [2]:
import numpy as np
arr1 = np.array ( [1,2,3])
arr2 = np.array ( [9,8,5])
sum = np.add (arr1, arr2)
print (sum)


[10 10  8]


2. Write a Python Program to find largest element in an array?

In [5]:
arr3 = np.random.randint (100, size= (3,5))
print (arr3)
print (arr3.max())

[[59 16 84 24 34]
 [95 84 70  0 94]
 [95 54 12 97 79]]
97


3. Write a Python Program for array rotation?

In [23]:
# n is length of an array. 
# d is the number by which you want to rotate the array
def leftRotate(arr, d, n):
    for i in range(d):
        temp = arr[0]
        for j in range(n-1):
            arr[j] = arr[j+1]
        arr[n-1] = temp
    print (arr)

arr2 = np.array ( [1,2,3,4,5,6,7 ])
leftRotate ( arr2, 3, 7 )

[4 5 6 7 1 2 3]


4. Write a Python Program to Split the array and add the first part to the end?

In [26]:
# n is length of an array. 
# d is the index number from which you want to split the array
def split_rotate(arr, d, n):
    for i in range(d):
        temp = arr[0]
        for j in range(n-1):
            arr[j] = arr[j+1]
        arr[n-1] = temp
    print (arr)

arr2 = np.array ( [15,23,3,4,5,6,7])
split_rotate (arr2, 3, 7)


[ 4  5  6  7 15 23  3]


5. Write a Python Program to check if given array is Monotonic?

In [31]:
def check_monotonic (arr): 
    list1 = []
    list2 = [] 
    for i in range (len (arr)-1): 
        list1.append (arr[i]<= arr [i+1])
        list2.append (arr[i]>= arr [i+1])
    if all (list1) or all (list2): 
        print ("the given array is monotonic")
    else : 
        print ( "the given array is monotonic not monotonic")
arr4= np.array ([1,10,12,13,15,406,1003])
arr5= np.array ([1,10,12,13,15,406,1003, 48])
arr6= np.array ([100,56,45,41,15,3,2])
arr7= np.array ([100,56,45,41,15,3,2 ,48])
check_monotonic (arr4)
check_monotonic (arr5)
check_monotonic (arr6)
check_monotonic (arr7)

    
            

the given array is monotonic
the given array is monotonic not monotonic
the given array is monotonic
the given array is monotonic not monotonic
